email:
  fromEmail: zubaer.haque@gmail.com
  fromName: 'Zubaer Haque''s Blog'
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  abdb4c54-c826-4751-a26a-1c98d27ac020:
    name: Common
siteGroups:
  ccf18982-bc90-4b03-bf09-d0d35dea6f68:
    name: 'Zubaer Haque''s Blog'
sites:
  e1cbf2f9-12b8-489b-94a6-ce3308cdb40e:
    baseUrl: $DEFAULT_SITE_URL
    handle: default
    hasUrls: true
    language: en-US
    name: 'Zubaer Haque''s Blog'
    primary: true
    siteGroup: ccf18982-bc90-4b03-bf09-d0d35dea6f68
    sortOrder: 1
system:
  edition: solo
  live: true
  name: 'Zubaer Haque''s Blog'
  schemaVersion: 3.1.25
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
